# Nextclade parameters to include if you are running Nextclade as a part of your ingest workflow
# Note that this requires a Nextclade dataset to already exist for your pathogen.
nextclade:
  # The name of the Nextclade dataset to use for running nextclade.
  # Run `nextclade dataset list` to get a full list of available Nextclade datasets
  dataset_name: ""
  # The first column should be the original column name of the Nextclade TSV
  # The second column should be the new column name to use in the final metadata TSV
  # Nextclade can have pathogen specific output columns so make sure to check which
  # columns would be useful for your downstream phylogenetic analysis.
  field_map:
    seqName: "seqName"
    clade: "clade"
    coverage: "coverage"
    totalMissing: "missing_data"
    totalSubstitutions: "divergence"
    totalNonACGTNs: "nonACGTN"
    qc.missingData.status: "QC_missing_data"
    qc.mixedSites.status: "QC_mixed_sites"
    qc.privateMutations.status: "QC_rare_mutations"
    qc.frameShifts.status: "QC_frame_shifts"
    qc.stopCodons.status: "QC_stop_codons"
    frameShifts: "frame_shifts"
  # This is the ID field you would use to match the Nextclade output with the record metadata.
  # This should be the new name that you have defined in your field map.
  id_field: "seqName"
