# Use default configuration values. Override with Snakemake's --configfile/--config options.
configfile: "config/defaults.yaml"


include: "rules/fetch_from_ncbi.smk"
include: "rules/curate.smk"

if "nextclade" in config:
    include: "rules/nextclade.smk"
