# This configuration file should contain all required configuration parameters
# for the ingest workflow to run to completion.
#
# Define optional config parameters with their default values here so that users
# do not have to dig through the workflows to figure out the default values

# Required to fetch from Entrez
entrez_search_term: ""

# Required to fetch from NCBI Datasets
ncbi_taxon_id: ""

# Optional fields to add to the NCBI Datasets output
ncbi_dataset_fields: []

# Config parameters related to the curate pipeline
curate:
  # URL pointed to public generalized geolocation rules
  # For the Nextstrain team, this is currently
  # 'https://raw.githubusercontent.com/nextstrain/ncov-ingest/master/source-data/gisaid_geoLocationRules.tsv'
  geolocation_rules_url: ""
  # The path to the local geolocation rules within the pathogen repo
  # The path should be relative to the ingest directory.
  local_geolocation_rules: "config/geolocation_rules.tsv"
  # List of field names to change where the key is the original field name and the value is the new field name
  # This is the first step in the pipeline, so any references to field names
  # in the configs below should use the new field names
  # The examples below are based on the NCBI Datasets output TSV column names, your data might have different field names.
  field_map:
    Source database: database
    Isolate Collection date: date
    Release date: date_released
    Update date: date_updated
    Accession: accession
    Isolate Lineage: strain
    Geographic Region: region
    Geographic Location: location
    Submitter Names: authors
    Submitter Affiliation: institution
    SRA Accessions: sra_accessions
    Length: length
    Host Name: host
    Isolate Lineage source: sample_type
    BioSample accession: biosample_accession
    Submitter Country: submitter_country
  # Standardized strain name regex
  # Currently accepts any characters because we do not have a clear standard for strain names across pathogens
  strain_regex: '^.+$'
  # Back up strain name field to use if 'strain' doesn't match regex above
  strain_backup_fields: ['accession']
  # List of date fields to standardize to ISO format YYYY-MM-DD
  date_fields: []
  # List of expected date formats that are present in the date fields provided above
  # These date formats should use directives expected by datetime
  # See https://docs.python.org/3.9/library/datetime.html#strftime-and-strptime-format-codes
  expected_date_formats: []
  titlecase:
    # List of string fields to titlecase
    fields: []
    # List of abbreviations not cast to titlecase, keeps uppercase
    abbreviations: []
    # Articles that should not be cast to titlecase
    articles: []
  # Metadata field that contains the list of authors associated with the sequence
  authors_field: ""
  # Default value to use if the authors field is empty
  authors_default_value: ""
  # Name to use for the generated abbreviated authors field
  abbr_authors_field: ""
  # Path to the manual annotations file
  # The path should be relative to the ingest directory
  annotations: "config/annotations.tsv"
  # The ID field in the metadata to use to merge the manual annotations
  annotations_id: ""
  # The ID field in the metadata to use as the sequence id in the output FASTA file
  output_id_field: ""
  # The field in the NDJSON record that contains the actual genomic sequence
  output_sequence_field: ""
  # The list of metadata columns to keep in the final output of the curation pipeline.
  metadata_columns: []


# Nextclade parameters to include if you are running Nextclade as a part of your ingest workflow
# Note that this requires a Nextclade dataset to already exist for your pathogen.
# Remove the following parameters if you do not plan to run Nextclade.
nextclade:
  # The name of the Nextclade dataset to use for running nextclade.
  # Run `nextclade dataset list` to get a full list of available Nextclade datasets
  dataset_name: ""
  # Path to the mapping for renaming Nextclade output columns
  # The path should be relative to the ingest directory
  field_map: "config/nextclade_field_map.tsv"
  # This is the ID field you would use to match the Nextclade output with the record metadata.
  # This should be the new name that you have defined in your field map.
  id_field: "seqName"
